/**
 * Auto-generated by `pnpm db:types` (supabase gen types typescript --local).
 * Do NOT edit by hand. Run the script after migrations.
 *
 * Until the local Supabase is running and types are generated, this is a
 * permissive `any` placeholder so the rest of the workspace type-checks.
 * The "real" generated file will replace this in Phase 0 Week 1's
 * local-dev setup and tighten everything back up.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
